######################
#    USER CONFIG     #
######################

# For the wifi to connect to
WIFI_SSID			 = your_ssid
WIFI_PASW			 = 123-not-secure

# For the webshop to connect to
SERVER_URL		 = https://www.my-presta-shop.de
SERVER_PORT		 = 443
SERVER_API_KEY = your-generated-api-key

######################
# END OF USER CONFIG #
######################
